services:
  - type: web
    name: digital-twin-factory
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main_final_separate:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
